# Generated by Django 4.0.6 on 2022-08-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestion',
            name='on_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
