# Generated by Django 4.0.6 on 2022-08-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_forumquestion_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestion',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
