# Generated by Django 4.0.5 on 2022-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='incorrect_answers',
            field=models.JSONField(),
        ),
    ]
