# Generated by Django 4.0.5 on 2022-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_quiz_incorrect_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='incorrect_answers',
            field=models.CharField(max_length=10),
        ),
    ]
