# Generated by Django 4.0.5 on 2022-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
