# Generated by Django 4.0.5 on 2022-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_leaderboard_user_alter_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='on_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
