# Generated by Django 4.0.5 on 2022-07-18 06:26

from django.db import migrations, models
import userapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=userapi.models.setUserImage),
        ),
    ]
