# Generated by Django 4.0.5 on 2022-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='yourClass',
            field=models.CharField(blank=True, max_length=20, verbose_name='yourClass'),
        ),
    ]
