# Generated by Django 4.0.5 on 2022-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_user_address_user_mobile_user_yourclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=255, verbose_name='address'),
        ),
    ]
