# Generated by Django 4.0.5 on 2022-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_alter_user_address_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is_staff'),
        ),
    ]
